/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.securitytrip;

import javax.swing.*;

public class App {
    public static void main(String[] args) {
        // Запуск приложения в потоке EDT
        SwingUtilities.invokeLater(() -> {
            // Создаем окно
            JFrame frame = new JFrame("My Swing App");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(400, 300);

            // Добавляем кнопку
            JButton button = new JButton("Click Me!");
            button.addActionListener(e -> JOptionPane.showMessageDialog(frame, "Hello, Swing!"));
            frame.add(button);

            // Отображаем окно
            frame.setVisible(true);
        });
    }
}
